[tool.poetry]
name = "hw-27"
version = "0.1.0"
description = ""
authors = ["moriohgoose <maria51m@mail.ru>"]
readme = "README.md"
packages = [{include = "hw_27"}]

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
